### ISSUE TITLE
Make Transport Factory a first class object

### ISSUE THREAD

**Issue by mikemix** [zendframework/zend-mail#106]
Please remove the `abstract` keyword from the [Factory](https://github.com/zendframework/zend-mail/blob/master/src/Transport/Factory.php), so the class can be reused, not only inherited.

We want composition over inheritance, don't we?

**Comment by weierophinney** [comment]
You missed the point; it's abstract because:

- it only exposes a single static method
- it is not intended to be instantiated

If we were to make it instantiable, we'd likely mark it final as it would only expose the single method, making inheritance moot anyways.
