### ISSUE TITLE
Excess <> characters in message-id header

### ISSUE THREAD

**Issue by yurikuzn** [zendframework/zend-mail#111]
When email being parsed it retrieves message id header value

```
<<message-id>>
```

instead of

```
<message-id>
```

https://github.com/zendframework/zend-mail/blob/master/src/Header/MessageId.php#L79

**Comment by mikegioia** [comment]
I've encountered this as well. This could be a very quick PR if a maintainer could confirm the following fix:

~`$this->messageId = sprintf('<%s>', $id);`~

`+        $this->messageId = sprintf('<%s>', trim($id, '<>'));`

**Comment by samsonasik** [comment]
should already fixed at 2.9.0 https://github.com/zendframework/zend-mail/commit/4c785563fe455c625b543ac5ea6eea29fb2589c1

**Comment by mikegioia** [comment]
@samsonasik Yea that looks like it, thanks!

**Comment by glensc** [comment]
@yurikuzn close this please, as maintainers do not look issues it seems

see https://github.com/zendframework/zend-mail/issues/111#issuecomment-369985023
