### ISSUE TITLE
Empty Sender header

### ISSUE THREAD

**Issue by yurikuzn** [zendframework/zend-mail#112]
When sending email using Zend SMTP transport it adds Sender header with empty value if this header was not defined:

```
Sender: 
```

If you parse such an email using Zend Imap it throws an error:

```
Zend\Mail\Header\Exception\InvalidArgumentException: Invalid header value for Sender string
```

**Comment by eth8505** [comment]
This was fixed with 2.7.3 https://github.com/zendframework/zend-mail/pull/93
