### ISSUE TITLE
Zend_Mail SMTP SSL Problem with PHP 5.6

### ISSUE THREAD

**Issue by ermajn** [zendframework/zend-mail#14]
I'm having same problem as below so I'm copying one forum post here hoping for some kind of solution.

PHP 5.6 changed the SSL certificate verification default, causing Zend_Mail SMTP to fail when the server CN doesn't exactly match the certificate CN. The solution to this is to set the verify_peer and verify_peer_name stream context options to false, but Zend_Mail provides no way to do this. The only workaround is to not use SSL in this instance, which means potentially sending userID/password in the clear.

The most flexible solution would be to have the Zend_Mail_Transport and Zend_Mail_Protocol classes accept config values to set stream context options, similar to the following:

$smtpOpts['_context_opt'] = array('ssl' => array('verify_peer' => 0, 'verify_peer_name' => 0));

Where 'ssl' is the context wrapper containing an array of context option name/value pairs.

A more limited solution would be to allow some kind of direct option that would indicate that the certificate should not be validated, and set the above context options accordingly.

**Comment by Maks3w** [comment]
@ermajn Seems you are using ZF1 not ZF2 version. Please open your issue in ZF1 issue tracker https://github.com/zendframework/zf1/issues
