### ISSUE TITLE
mail is going into spam and taking too long to deliver.

### ISSUE THREAD

**Issue by srivi1225** [zendframework/zend-mail#152]
Hi,
 I have written mail fuctionality like below and the mail is going to spam always and it is taking too long to deliver the mail.
```
$message = new Message();
        $message->setTo(
            'abc@xyz.com',
            'user name'
        );

        $message->setFrom("admin@xyz.com", "xyz");
        $message->setSubject("subject");
        $message->setReplyTo('admin@xyz.com', 'xyz');

        $message->setBody("sample email");
        $mail = new Mail();
        $mail->send($message);
```
i tried adding the headers like below but no luck.

```
$message = new Message();
        $message->setTo(
            'abc@xyz.com',
            'user name'
        );

        $message->getHeaders()->addHeaderLine('MIME-Version', '1.0');
        $message->getHeaders()->addHeaderLine('Content-Type', 'text/html');
        $message->getHeaders()->addHeaderLine('Content-Transfer-Encoding', '8bit');
        $message->getHeaders()->addHeaderLine('X-Mailer:', 'PHP/'.phpversion());

         $message->setFrom("admin@xyz.com", "xyz");
        $message->setSubject("subject");
        $message->setReplyTo('admin@xyz.com', 'xyz');

        $message->setBody("sample email");
        $mail = new Mail();
        $mail->send($message);
```

Please suggest me what i am doing wrong here and how to fix it to send the email to inbox instead of spam.

**Comment by weierophinney** [comment]
The reason messages are marked as spam generally have to do with configuration of the mail transport server via which the email is sent. Based on your above example, you're likely using the default transport, which send via the system "sendmail" binary; this could be sendmail, postfix, ssmtp, or one of a dozen other MTAs depending on what OS you use.

You will need to research what MTA your system uses to send emails, and how to configure it correctly so as to avoid other servers from flagging mail from it as spam. This is a complex subject, and difficult to get right. As such, the better solution is to use known good providers such as Gmail, or commercial transactional email providers that use SMTP.
