### ISSUE TITLE
Changelog looks weird.

### ISSUE THREAD

**Issue by paragonie-scott** [zendframework/zend-mail#154]
https://github.com/zendframework/zend-mail/blob/989eb321fa5b3f32c7ec22f5f057961901ecaad1/CHANGELOG.md

Looks like the fixes for #140 and #141 are being added to the 2.7.3 entry instead of starting a fresh one (presumably 2.7.4).

**Comment by paragonie-scott** [comment]
Fixed :)

**Comment by glensc** [comment]
link?

**Comment by froschdesign** [comment]
@glensc 
See the release notes for 2.8.0: https://github.com/zendframework/zend-mail/releases
