### ISSUE TITLE
Online DOC out of date

### ISSUE THREAD

**Issue by Slamdunk** [zendframework/zend-mail#162]
Both

- https://zendframework.github.io/zend-mail/transport/smtp-authentication/
- https://docs.zendframework.com/zend-mail/transport/smtp-authentication/

Are out of date compared to https://github.com/zendframework/zend-mail/blob/release-2.8.0/doc/book/transport/smtp-authentication.md

**Comment by froschdesign** [comment]
@Slamdunk 
The documentation has been rebuilt.

Thanks for reporting! 👍
