### ISSUE TITLE
Zend_Mail_Transport_Exception' with message 'Unable to send mail.

### ISSUE THREAD

**Issue by eakenbor** [zendframework/zend-mail#168]
I am unable to send out newsletters and transactional emails. The error shown in the exception log says:

"Zend_Mail_Transport_Exception' with message 'Unable to send mail."

Please can someone suggest what I should do to solve this problem? 

I am using Magento 1.9.2.2

**Comment by Ocramius** [comment]
@eakenbor `Zend_Mail` is part of ZendFramework 1.x, which is no longer supported.

**Comment by eakenbor** [comment]
@Ocramius Please how do I solve the problem? Any recommendation? What should I uninstall and replace it with? Please throw more light. Thanks.

**Comment by Ocramius** [comment]
@eakenbor this is a question for magento core and their forums, not this one. The error seems simple though: your mailer configuration is unable to send mails.

**Comment by eakenbor** [comment]
Thanks @Ocramius. I am utter novice in this stuff and I will appreciate all you help. I have 2 Magento experts working on this since 3 days now and yet no way out. Please can you direct me on the steps I need to take to resolve this? Please!

**Comment by Ocramius** [comment]
No, sorry. As said, `Zend_Mail` is no longer maintained, so you need to ask on the Magento forums.

Also, if you already have folks working on it, then you should rely on them first.

**Comment by eakenbor** [comment]
@Ocramius The Magento guys have given up. They say the problem is with the hosting server. Godaddy says the problem is not theirs. Now I am stuck and confused. If Zend_Mail is no more maintained, what is the latest one in the Zendframework I can replace it with?

**Comment by Ocramius** [comment]
@eakenbor this package is for `Zend\Mail` 2.x: you are using `Zend_Mail` 1.x, which is from ZendFramework 1, which was abandoned last year: https://framework.zend.com/blog/2016-06-28-zf1-eol.html

Also, your problem is likely just with the internal [`mail()` function of PHP](https://secure.php.net/manual/en/function.mail.php). Try debugging around the simple `mail()` function to check if it sends anything.
