### ISSUE TITLE
Migration from Zend Framework 1 to 2

### ISSUE THREAD

**Issue by eakenbor** [zendframework/zend-mail#169]
Please I need to migrate from Zend Framework 1 to 2 or 3. Can anyone advise how I can go about it? Thanks.

**Comment by RalfEggert** [comment]
@eakenbor 

Please go to the Discourse Form to ask your migration question. This issue tracker is not a support forum. But you will get help there if you  add some more information:

https://discourse.zendframework.com/

Thanks!
