### ISSUE TITLE
dependecy for service manager

### ISSUE THREAD

**Issue by mhf-ir** [zendframework/zend-mail#175]
https://zendframework.slack.com/archives/C4QBQUEG5/p1508609218000053

It's require this package i'v got an error during using as library:
```
<br />
<b>Fatal error</b>:  Class 'Zend\ServiceManager\AbstractPluginManager' not found in <b>/app/app/vendor/zendframework/zend-mail/src/Protocol/SmtpPluginManager.php</b> on line <b>22</b><br />
```

if suggestion package so create mechanism for check it.

**Comment by glen-84** [comment]
See #62.

**Comment by Ocramius** [comment]
Closing as `duplicate`
