### ISSUE TITLE
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\Smtp.php on line 215

### ISSUE THREAD

**Issue by sakinaaf** [zendframework/zend-mail#238]

**Comment by froschdesign** [comment]
@sakinaaf 
Please stop open new issue reports. This is a bug tracker and not a support forum.

**Explain your problem** with code examples in the [forum](https://discourse.zendframework.com/) otherwise we can not help you!

Thanks!
