### ISSUE TITLE
Comma in Sender Name

### ISSUE THREAD

**Issue by sPooKee** [zendframework/zend-mail#43]
Hello,

I have an E-Mail with the following "From"-Header:

`From: =?UTF-8?Q?Lastname,=20Prename=20(Company=20GmbH)=20<prename@company.de>?=`

After decoding in Zend\Mail\AddressList\AbstractAddressList (`HeaderWrap::mimeDecodeValue($fieldValue);`) it looks like this:

`Lastname, Prename (Company GmbH) <prename@company.de>`

After `$values     = str_getcsv($fieldValue, ',');` $values is:

```
array(1) {
  [0]=>
  array(2) {
    [0]=>
    string(6) "Lastname"
    [1]=>
    string(24) "Prename  <prename@company.de>"
  }
}
```

This leads to the following Error:

````
The input is not a valid email address. Use the basic format local-part@hostname

#0 /htdocs/vendor/zendframework/zend-mail/src/AddressList.php(249): Zend\Mail\Address->__construct('Lastname', NULL)
#1 /htdocs/vendor/zendframework/zend-mail/src/AddressList.php(35): Zend\Mail\AddressList->createAddress('Lastname', NULL)
#2 /htdocs/vendor/zendframework/zend-mail/src/AddressList.php(113): Zend\Mail\AddressList->add('Lastname', NULL)
#3 /htdocs/vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php(75): Zend\Mail\AddressList->addFromString('Lastname')
```

Any Idea how to fix this?

**Comment by mleko** [comment]
https://github.com/zendframework/zend-mail/pull/44
