### ISSUE TITLE
Zend Mail Pop3 - Invalid header value detected

### ISSUE THREAD

**Issue by stmaxvl** [zendframework/zend-mail#50]
I use Zend\Mail\Storage\Pop3 to get message.
ZF Version 2.5.1

Code:

$mail = new \Zend\Mail\Storage\Pop3(
array(
'host' => '...',
'user' => '...',
'password' => '...',
'ssl' => 'SSL'
));
$count = $mail->countMessages();
for($messageNum=1; $messageNum<=$count; $messageNum++){
$message = $mail->getMessage($messageNum);
}

Trace error:

Invalid header value detected#0 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Header\GenericHeader.php(35): Zend\Mail\Header\GenericHeader::splitHeaderLine('Subject: \xD0\x9E\xD1\x84\xD0\xBB...')
#1 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Headers.php(231): Zend\Mail\Header\GenericHeader::fromString('Subject: \xD0\x9E\xD1\x84\xD0\xBB...')
#2 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Headers.php(95): Zend\Mail\Headers->addHeaderLine('Subject: \xD0\x9E\xD1\x84\xD0\xBB...')
#3 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Storage\Part.php(108): Zend\Mail\Headers::fromString('X-Yandex-Folder...')
#4 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Storage\Message.php(54): Zend\Mail\Storage\Part->__construct(Array)
#5 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Storage\Pop3.php(65): Zend\Mail\Storage\Message->__construct(Array)
#6 C:\xampp\htdocs\master4u\module\PpModuleMailer\src\PpModuleMailer\Controller\ConsoleController.php(82): Zend\Mail\Storage\Pop3->getMessage(1)

**Comment by ianfp** [comment]
I have the same problem with zend-mail v2.7.0. The header line that is triggering the error is:

    Received: from R4GUI ([172.16.4.193]) by R4GUI.freedfm.com with Microsoft SMTPSVC(6.0.3790.4675);	 Thu, 28 Apr 2016 08:28:30 -0600

**Comment by luigimeclea** [comment]
Same here with zend-mail 2.7.0 on IMAP:

Type: Zend\Mail\Header\Exception\InvalidArgumentException
Message: Invalid header value detected
File: /vendor/zendframework/zend-mail/src/Header/GenericHeader.php
Line: 61

The header that's causing the problem, because of the tab character \t:

 from 127.0.0.1 (localhost.localdomain [127.0.0.1])	by el4.banat.enelro (8.13.8/8.13.8) with SMTP id u42G95eK008742	for <*@gmail.com>; Mon, 2 May 2016 19:09:05 +0300

**Comment by Maks3w** [comment]
Could you try with dev-master? (dev-master as 2.7.1)

**Comment by luigimeclea** [comment]
Fixed, thanks!

**Comment by Maks3w** [comment]
@weierophinney I let this open until the fix was tagged

**Comment by weierophinney** [comment]
@maks3w I'll be tagging momentarily. The point is that the issue is already resolved.
