### ISSUE TITLE
"Malformed header detected" on valid example from rfc7103 7.3

### ISSUE THREAD

**Issue by ftzdomino** [zendframework/zend-mail#92]
Per [RFC 7103 section 7.3](https://tools.ietf.org/html/rfc7103#section-7.3), having whitespace on an otherwise empty line is deprecated but still valid.  I'm running into this with emails generated by some Microsoft product. 

Code to reproduce the error:

``` php
require __DIR__.'/vendor/autoload.php';

$src = "From: user@example.com
To: userpal@example.net
Subject: This is your reminder

  about the football game tonight
Date: Wed, 20 Oct 2010 20:53:35 -0400

Don't forget to meet us for the tailgate party!
";
new Zend\Mail\Storage\Message(array('raw' => $src));
```

This results in:

```
PHP Fatal error:  Uncaught exception 'Zend\Mail\Exception\RuntimeException' with message 'Malformed header detected' in vendor/zendframework/zend-mail/src/Headers.php:88
vendor/zendframework/zend-mail/src/Headers.php:88
vendor/zendframework/zend-mime/src/Decode.php:142
vendor/zendframework/zend-mail/src/Storage/Part.php:105
vendor/zendframework/zend-mail/src/Storage/Message.php:54
```

 One workaround is to use pipe the message source through formail first and tell it to merge header lines:  
`formail -c -f`

**Comment by Maks3w** [comment]
Could you provide the value of `$src` as a single line using `\n \r \t ...`

**Comment by ftzdomino** [comment]
```php
<?php
require __DIR__.'/vendor/autoload.php';

$src = "From: user@example.com\nTo: userpal@example.net\nSubject: This is your reminder\n  \n  about the football game tonight\nDate: Wed, 20 Oct 2010 20:53:35 -0400\nDon't forget to meet us for the tailgate party!\n";
new Zend\Mail\Storage\Message(array('raw' => $src));
```

**Comment by Maks3w** [comment]
@ftzdomino Thx.

Do you will work on this and provide a patch (PR)?

**Comment by ftzdomino** [comment]
I'd love to help out, as this library has saved me the trouble of having to maintain my own copy of abandoned pear libs.  I'm a bit new to Zend projects and not totally familiar with the coding styles, so please bare with me.  Is it easier to paste patches in this discussion or submit pull requests for feedback?

**Comment by weierophinney** [comment]
@ftzdomino Pull requests are generally easier. The library has a CONTRIBUTING.md file that details how to create and submit those.

**Comment by samsonasik** [comment]
@weierophinney @ftzdomino I've created PR #196 for it
